#!/bin/bash
# multi-account-setup.sh - GitHub CLI 多帳號設定指南

echo "🔐 GitHub CLI 多帳號管理指南"
echo "================================"
echo ""

echo "📋 當前狀態："
echo "  - 已登入帳號: PoyuanShih-ASUS"  
echo "  - 目標倉庫: spyyy666/qgc-bazel"
echo "  - 問題: 帳號不匹配導致權限不足"
echo ""

echo "🔧 解決方案選項："
echo ""

echo "方案 1: 使用 spyyy666 帳號登入"
echo "  1. 暫時清除當前認證:"
echo "     unset GH_TOKEN"
echo "     gh auth logout"
echo ""
echo "  2. 登入 spyyy666 帳號:"
echo "     gh auth login"
echo "     # 選擇 GitHub.com"
echo "     # 選擇 HTTPS"
echo "     # 使用 web browser 認證"
echo "     # 使用 spyyy666 帳號登入"
echo ""

echo "方案 2: 設定多帳號環境"
echo "  1. 創建配置檔案:"
echo "     mkdir -p ~/.config/gh-profiles/spyyy666"
echo "     mkdir -p ~/.config/gh-profiles/PoyuanShih-ASUS"
echo ""
echo "  2. 創建切換腳本:"
echo "     # 切換到 spyyy666"
echo "     export GH_CONFIG_DIR=~/.config/gh-profiles/spyyy666"
echo "     gh auth login"
echo ""
echo "     # 切換到 PoyuanShih-ASUS"  
echo "     export GH_CONFIG_DIR=~/.config/gh-profiles/PoyuanShih-ASUS"
echo "     gh auth login"
echo ""

echo "方案 3: 直接使用瀏覽器 (推薦)"
echo "  1. 開啟: https://github.com/spyyy666/qgc-bazel/actions"
echo "  2. 找到 'Build QGroundControl for arm64 (Original Method)'"
echo "  3. 點擊 'Run workflow'"
echo "  4. 觀察執行結果"
echo ""

echo "📝 建議:"
echo "由於這只是測試原始 workflow 是否可用，"
echo "使用瀏覽器是最快最簡單的方法。"
echo ""
echo "如果經常需要命令列操作，再考慮設定多帳號。"