# .github/workflows/build-qgc-arm64.yml
name: 'Build QGroundControl for arm64'

on: [push, pull_request]

jobs:
  build-arm64:
    # 使用標準的 x86_64 runner，但透過 Docker 進行 ARM64 建構
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx for multi-platform
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU for ARM64 emulation
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Build QGroundControl in ARM64 Docker Container
      run: |
        docker run --rm \
          --platform linux/arm64 \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          ubuntu:22.04 \
          bash -c "
            # 安裝基本工具和依賴
            apt-get update && apt-get install -y --no-install-recommends \
              build-essential \
              curl \
              git \
              pkg-config \
              qt6-base-dev \
              qt6-declarative-dev \
              qt6-tools-dev \
              qt6-charts-dev \
              libgstreamer1.0-dev \
              libgstreamer-plugins-base1.0-dev \
              libgl1-mesa-dev \
              libegl1-mesa-dev \
              libglu1-mesa-dev \
              && \
            # 安裝 Bazelisk
            curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-arm64 -o /usr/local/bin/bazel && \
            chmod +x /usr/local/bin/bazel && \
            # 建構 QGroundControl（不需要交叉編譯配置，因為是原生 ARM64 環境）
            bazel build //:qgroundcontrol_cmake
          "

    - name: Extract built artifacts
      run: |
        # 從 Docker 容器中提取建構好的檔案
        docker run --rm \
          --platform linux/arm64 \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          ubuntu:22.04 \
          cp bazel-bin/qgroundcontrol_cmake/QGroundControl ./QGroundControl-arm64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: qgroundcontrol-arm64
        path: QGroundControl-arm64