# .github/workflows/release.yml
name: 'Release QGroundControl ARM64'

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx and QEMU
      uses: docker/setup-buildx-action@v3
      
    - name: Set up QEMU for ARM64 emulation
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
        
    - name: Build QGroundControl ARM64
      run: |
        docker run --rm \
          --platform linux/arm64 \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          ubuntu:22.04 \
          bash -c "
            apt-get update && apt-get install -y --no-install-recommends \
              build-essential curl git pkg-config \
              qt6-base-dev qt6-declarative-dev qt6-tools-dev qt6-charts-dev \
              libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
              libgl1-mesa-dev libegl1-mesa-dev libglu1-mesa-dev && \
            curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-arm64 -o /usr/local/bin/bazel && \
            chmod +x /usr/local/bin/bazel && \
            cp BUILD.bazel.native BUILD.bazel && \
            bazel build //:qgroundcontrol_cmake && \
            cp bazel-bin/qgroundcontrol_cmake/QGroundControl /workspace/QGroundControl-arm64
          "
          
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          QGroundControl-arm64
        body: |
          ## QGroundControl ARM64 Release
          
          **架構**: ARM64 (aarch64)
          **建構日期**: ${{ github.run_id }}
          
          ### 安裝需求：
          - ARM64 處理器
          - Ubuntu 22.04+ 或相容系統
          - Qt6 執行時庫
          
          ### 執行方式：
          ```bash
          chmod +x QGroundControl-arm64
          ./QGroundControl-arm64
          ```
        draft: false
        prerelease: false